repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Use uma versão estável específica
    hooks:
      - id: black
        language_version: python3.12  # ou a versão do Python que você está usando

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use uma versão estável específica
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Use uma versão estável específica
    hooks:
      - id: flake8
        args: [--max-line-length=88]  # Opcional: argumentos adicionais para Flake8
