repos:
  #  Formatador de Código
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.12
        args: [--exclude, '/(__init__\.py|tests/)']

  # Ordena importações de arquivos
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
  
  # Ferramenta de linting para avaliar qualidade do código, busca erros, estilos e padrões de código
  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.6
    hooks:
      - id: pylint
        args: [--disable=C0111, --max-line-length=9999999]
        exclude: ^tests/
        files: \.py$